Repository openimsdk/docs, pull requests merged in 2023-10, with the labels that each got.

#35 feat: Refactor the structure of the document
  .idea/.gitignore
  .idea/docs.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  scripts/githooks/commit-msg
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push
  scripts/githooks/pre-push.sh
Labels: size/XL

#39 fix: Delete some useless tabs.
  docs/sdks/api/group/setGroupMemberInfo.mdx
  docs/sdks/api/message/createImageMessageByURL.mdx
  docs/sdks/api/message/createTextAtAllMessage.mdx
  docs/sdks/api/message/setBatchMsgListener.mdx
  docs/sdks/callback/onConnectFailed.mdx
  docs/sdks/callback/onConnectSuccess.mdx
  docs/sdks/callback/onConnecting.mdx
  docs/sdks/callback/onError.mdx
  docs/sdks/callback/onKickedOffline.mdx
  docs/sdks/callback/onProgress.mdx
  docs/sdks/callback/onRecvNewMessages.mdx
  docs/sdks/callback/onRecvOfflineNewMessage.mdx
  docs/sdks/callback/onRecvOfflineNewMessages.mdx
  docs/sdks/callback/onUserTokenExpired.mdx
  docs/sdks/class/init/config.mdx
  docs/sdks/enum/handleResult.mdx
  docs/sdks/enum/joinSource.mdx
  docs/sdks/enum/loginStatus.mdx
  docs/sdks/enum/messageContentType.mdx
  docs/sdks/enum/messageStatus.mdx
  docs/sdks/enum/platform.mdx
  docs/sdks/enum/recvMsgOpt.mdx
  docs/sdks/enum/relationship.mdx
Labels: size/L

#41 fix: Corrected the API for obtaining user information when there is n…
  docs/sdks/api/user/getUsersInfoWithCache.mdx
Labels: size/S

#43 fix: Fixed some issues. (#42)
  docs/sdks/callback/onConnectFailed.mdx
  docs/sdks/callback/onConnectSuccess.mdx
  docs/sdks/callback/onConnecting.mdx
  docs/sdks/callback/onKickedOffline.mdx
  docs/sdks/callback/onProgress.mdx
  docs/sdks/callback/onSuccess.mdx
  docs/sdks/callback/onUserTokenExpired.mdx
  docs/sdks/enum/messageContentType.mdx
Labels: size/L
