Repository openimsdk/docs, pull requests merged in 2023-12, with the labels that each got.

#60 fix:js and wasm github url
  docs/guides/gettingStarted/jssdk.mdx
Labels: size/XS

#61 feat: tarns the webhook docs
  docs/restapi/apis/messageManagement/getConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/messageManagement/getConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/applyJoinGroupBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/create.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/createAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/createBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/disMissGroupAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/groupMsgRead.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/inviteJoinGroupBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/joinGroupAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/killGroupMember.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/quitGroup.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/sendGroupMsgAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/sendGroupMsgBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setMemberInfoAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setMemberInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/transferGroupOwnerAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/create.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/msgModify.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/sendSingleMsgAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/sendSingleMsgBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/singleMsgRead.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/singleMsgRevokeAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/push/create.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/push/offlinePushBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/push/onlinePushBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/push/superGroupOnlinePushBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/addBlack.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/addFriendAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/addFriendAgreeBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/addFriendBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/create.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/deleteFriendAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/importFriendAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/importFriendsBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/removeBlack.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/setFriendRemarkAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/setFriendRemarkBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/create.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userOffline.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userOnline.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userRegisterAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userRegisterBefore.mdx
Labels: size/XXL

#62 fix: fix the trans error
  docs/restapi/webhooks/example.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/introduction.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/introduction.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/example.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/groupMsgRead.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/killGroupMember.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/sendGroupMsgAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/singleMsgRevokeAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/relationship/addFriendAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userOffline.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userOnline.mdx
Labels: size/L

#64 update pressure test
  docs/guides/introduction/images/bandwidth-usage-10w.png
  docs/guides/introduction/images/bandwidth-usage-5w.png
  docs/guides/introduction/images/client-check-result-10w.png
  docs/guides/introduction/images/client-check-result-5w.png
  docs/guides/introduction/images/cpu-qps-usage-10w.png
  docs/guides/introduction/images/cpu-qps-usage-5w.png
  docs/guides/introduction/images/cpu-usage-10wonline.png
  docs/guides/introduction/images/cpu-usage-5wonline.png
  docs/guides/introduction/images/disk-usage-10w.png
  docs/guides/introduction/images/disk-usage-5w.png
  docs/guides/introduction/images/memory-usage-10w.png
  docs/guides/introduction/images/memory-usage-5w.png
  docs/guides/introduction/pressure_test.md
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/updateFriends.mdx
Labels: size/L

#66 add:add prometheus dock
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/assets/admin1.png
  docs/guides/gettingStarted/assets/alert1.png
  docs/guides/gettingStarted/assets/alert2.png
  docs/guides/gettingStarted/assets/alert3.png
  docs/guides/gettingStarted/assets/alert4.png
  docs/guides/gettingStarted/assets/dashboard.png
  docs/guides/gettingStarted/assets/dashboard2.png
  docs/guides/gettingStarted/assets/dashboard3.png
  docs/guides/gettingStarted/assets/dashboard4.png
  docs/guides/gettingStarted/assets/dashboard5.png
  docs/guides/gettingStarted/assets/database.png
  docs/guides/gettingStarted/assets/database2.png
  docs/guides/gettingStarted/assets/docker-compose1.png
  docs/guides/gettingStarted/assets/docker-compose2.png
  docs/guides/gettingStarted/assets/login.png
Labels: size/M

#67 docs: Update error description in checkUserRegistered.mdx
  docs/restapi/apis/userManagement/checkUserRegistered.mdx
Labels: size/XS

#69 fix: fix the GetConversationAPI
  docs/restapi/apis/conversationManagement/getConversationList.mdx
  docs/restapi/apis/messageManagement/getConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getConversationList.mdx
Labels: size/XL

#77 fix:fix mdx
  docs/guides/gettingStarted/admin.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/admin.mdx
Labels: size/S
