Repository openimsdk/docs, pull requests merged in 2023-08, with the labels that each got.

#11 add chat api doc
  .idea/.gitignore
  .idea/docs.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/vcs.xml
  docs/restapi/chat/admin/admin_account/login.mdx
  docs/restapi/chat/admin/admin_account/searchInfo.mdx
  docs/restapi/chat/admin/admin_account/updateInfo.mdx
  docs/restapi/chat/admin/applet/add.mdx
  docs/restapi/chat/admin/applet/delete.mdx
  docs/restapi/chat/admin/applet/search.mdx
  docs/restapi/chat/admin/applet/update.mdx
  docs/restapi/chat/admin/client_configuration/delete.mdx
  docs/restapi/chat/admin/client_configuration/get.mdx
  docs/restapi/chat/admin/client_configuration/set.mdx
  docs/restapi/chat/admin/register_management/IP/forbidden/user/add.mdx
  docs/restapi/chat/admin/register_management/IP/forbidden/user/delete.mdx
  docs/restapi/chat/admin/register_management/IP/forbidden/user/search.mdx
  docs/restapi/chat/admin/register_management/default_friend/add.mdx
  docs/restapi/chat/admin/register_management/default_friend/delete.mdx
  docs/restapi/chat/admin/register_management/default_friend/list.mdx
  docs/restapi/chat/admin/register_management/default_friend/search.mdx
  docs/restapi/chat/admin/register_management/default_group/add.mdx
  docs/restapi/chat/admin/register_management/default_group/delete.mdx
  docs/restapi/chat/admin/register_management/default_group/list.mdx
  docs/restapi/chat/admin/register_management/default_group/search.mdx
  docs/restapi/chat/admin/register_management/invitaion_code/add.mdx
  docs/restapi/chat/admin/register_management/invitaion_code/delete.mdx
  docs/restapi/chat/admin/register_management/invitaion_code/generate.mdx
  docs/restapi/chat/admin/register_management/invitaion_code/search.mdx
  docs/restapi/chat/admin/stastatic/user/add_user.mdx
  docs/restapi/chat/admin/stastatic/user/login_user.mdx
  docs/restapi/chat/admin/user_management/block/add.mdx
  docs/restapi/chat/admin/user_management/block/delete.mdx
  docs/restapi/chat/admin/user_management/block/search.mdx
  docs/restapi/chat/admin/user_management/user/reset_password.mdx
  docs/restapi/chat/admin/work_moment/delete.mdx
  docs/restapi/chat/admin/work_moment/forbidden_publish.mdx
  docs/restapi/chat/admin/work_moment/search.mdx
Labels: size/XXL

#20 Added 'onUserStatusChanged' callback function.
  docs/sdks/api/user/setUserListener.mdx
  docs/sdks/callback/onUserStatusChanged.mdx
  docs/sdks/listener/userListener.mdx
Labels: size/M

#21 19 bug added onuserstatuschanged callback function
  docs/sdks/api/message/uploadFile.mdx
  docs/sdks/api/user/setUserListener.mdx
  docs/sdks/class/user/index.mdx
  docs/sdks/class/user/userStatusInfo.mdx
Labels: size/L

#23 no message
  docs/sdks/enum/messageContentType.mdx
Labels: size/S

#25 Update 'onGroupDismissed' callback function.
  docs/sdks/callback/onGroupDismissed.mdx
Labels: size/XS

#27 Update the Elem field related to the message.
  docs/sdks/callback/index.mdx
  docs/sdks/callback/onRecvMessageExtensionsAdded.mdx
  docs/sdks/callback/onRecvMessageExtensionsChanged.mdx
  docs/sdks/callback/onRecvMessageExtensionsDeleted.mdx
  docs/sdks/class/message/atElem.mdx
  docs/sdks/class/message/keyValue.mdx
  docs/sdks/class/message/keyValues.mdx
  docs/sdks/class/message/textElem.mdx
  docs/sdks/class/message/typingElem.mdx
Labels: size/L

#29 Update group type and permission enumeration.
  docs/sdks/enum/groupType.mdx
  docs/sdks/enum/roleLevel.mdx
Labels: size/S
