Repository openimsdk/docs, pull requests merged in 2024-01, with the labels that each got.

#82 Update main-ci.yaml
  .github/workflows/main-ci.yaml
Labels: size/XS

#81 feat: add openim docs update node version: latest
  .github/workflows/main-ci.yaml
Labels: size/S

#80 Improve documentation
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/assets/alert1.png
  docs/guides/gettingStarted/assets/alert2.png
Labels: size/L

#88 Feature/grafana doc
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/assets/admin1.png
  docs/guides/gettingStarted/assets/login.png
  docs/guides/gettingStarted/assets/login1.png
Labels: size/L

#93 fix:fix doc
  docs/guides/gettingStarted/assets/alert6.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/admin.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/admin1.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/alert1.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/alert2.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/alert6.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/login.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/login1.png
Labels: size/L

#96 fix: fix the notificationAccounts docs error
  docs/restapi/apis/conversationManagement/getConversationList.mdx
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  docs/restapi/apis/userManagement/updateNotificationAccount.mdx
  docs/restapi/webhooks/example.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/addNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateNotificationAccount.mdx
Labels: size/L

#97 fix: fix the getConversation docs error
  docs/restapi/apis/conversationManagement/getConversationList.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx
Labels: size/L

#98 fix: fix the addnotification docs
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/addNotificationAccount.mdx
Labels: size/M

#99 fix: fix the docs
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  docs/restapi/webhooks/group/applyJoinGroupBefore.mdx
  docs/restapi/webhooks/group/createAfter.mdx
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/disMissGroupAfter.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/quitGroup.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/group/sendGroupMsgBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setMemberInfoAfter.mdx
  docs/restapi/webhooks/group/setMemberInfoBefore.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/msg/msgModify.mdx
  docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx
  docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/push/superGroupOnlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeBefore.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/removeBlack.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/addNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx
Labels: size/L

#100 fix: fix the inviteJoinGroupBefore and transferGroupOwnerAfter docs
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/superGroupOnlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/push/superGroupOnlinePushBefore.mdx
Labels: size/L

#103 Update build-ci.yaml
  .github/workflows/build-ci.yaml
Labels: size/XS

#102 fix: fix the getSortedConversationList docs
  docs/restapi/apis/conversationManagement/getSortedConversationList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getSortedConversationList.mdx
Labels: size/L

#104 fix: fix the webhook en docs
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/example.mdx
Labels: size/XS

#108 fix error
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/friend/checkFriend.mdx
Labels: size/XS

#105 feat: add the nginxConfig
  docs/guides/gettingStarted/assets/nginx_ssl.png
  docs/guides/gettingStarted/nginxDomainConfig.mdx
Labels: size/L

#110 feat: add webhook example
  docs/restapi/webhooks/assets/config.png
  docs/restapi/webhooks/assets/result.png
  docs/restapi/webhooks/assets/sendMessage.png
  docs/restapi/webhooks/example.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/assets/config.png
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/assets/result.png
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/assets/sendMessage.png
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/example.mdx
Labels: size/L

#112 fix: func name in web tab
  docs/sdks/api/message/createImageMessageByURL.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/message/createImageMessageByURL.mdx
Labels: size/XS

#114 fix: fix the singleMsgRead webhook field and add a webhook example
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/msg/singleMsgRead.mdx
Labels: size/S

#116 fix: add dowload zip pkg deloyment way
  docs/guides/gettingStarted/dockerCompose.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/dockerCompose.mdx
Labels: size/XS

#117 docs(mac-deployment-guide.mdx): create openim mac source deployment docs
  docs/guides/gettingStarted/mac-deployment-guide.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/mac-deployment-guide.mdx
Labels: size/L

#118 fix: fix the callbackExample docs
  docs/restapi/webhooks/assets/config.png
  docs/restapi/webhooks/assets/defaultFriend.png
  docs/restapi/webhooks/example.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/assets/config.png
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/assets/defaultFriend.png
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/example.mdx
Labels: size/XL

#119 doc: uniapp quickstart doc update
  docs/sdks/quickstart/uniapp.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/quickstart/uniapp.mdx
Labels: size/M
