Repository openimsdk/docs, pull requests merged in 2024-12, with the labels that each got.

#221 feat: cluster deployment doc
  docs/guides/gettingStarted/cluster.assets/prometheus0.png
  docs/guides/gettingStarted/cluster.assets/rpc0.png
  docs/guides/gettingStarted/cluster.mdx
  docs/restapi/commonConfigs.mdx
  docs/restapi/webhooks/assets/config.jpg
  docs/restapi/webhooks/assets/config.png
  docs/restapi/webhooks/example.mdx
  docs/restapi/webhooks/introduction.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.assets/prometheus0.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.assets/rpc0.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.mdx
Labels: size/L

#223 feat: cluster doc
  docs/guides/gettingStarted/cluster.assets/prometheus0.png
  docs/guides/gettingStarted/cluster.assets/rpc0.png
  docs/guides/gettingStarted/cluster.mdx
Labels: size/M

#224 feat: cluster doc
  docs/guides/gettingStarted/cluster.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.assets/prometheus0.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.assets/rpc0.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/cluster.mdx
Labels: size/L

#227 add docs: faq and features
  docs/guides/gettingStarted/faq.mdx
  docs/guides/introduction/features.mdx
Labels: size/L

#226 docs: update kubernetes deployment docs contents.
  docs/guides/gettingStarted/k8s-deployment.mdx
Labels: size/L

#228 Add docs
  docs/guides/gettingStarted/cluster.mdx
  docs/guides/gettingStarted/env-comp.mdx
  docs/guides/gettingStarted/imSourceCodeDeployment.mdx
  docs/guides/introduction/termDefinition.mdx
  docs/guides/introduction/version.mdx
  docs/guides/solution/campareWithRocetchat.mdx
  docs/guides/solution/chooseProject.mdx
  docs/guides/solution/developNewFeatures.mdx
  docs/guides/solution/integrate.mdx
Labels: size/L

#211 fix: callback after register user remove secret
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/userRegisterAfter.mdx
Labels: size/XS

#218 fix: wrong table format of section modify common config items
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/imSourceCodeDeployment.mdx
Labels: size/XS

#230 docs: remove react native gradle
  docs/sdks/quickstart/reactNative.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/quickstart/reactNative.mdx
Labels: size/M

#231 feat: add doc about second development of server.
  docs/guides/solution/developNewFeatures.mdx
Labels: size/M

#232 feat: doc
  docs/guides/gettingStarted/faq.mdx
Labels: size/S

#234 feat: config doc
  docs/restapi/commonConfigs.mdx
Labels: size/S

#235 add s3 doc
  docs/guides/solution/s3.mdx
Labels: size/L

#236 add s3 doc
  docs/guides/solution/s3.mdx
Labels: size/M

#237 add docs
  docs/blog/golang/architectural/4.mdx
  docs/blog/introduction.mdx
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/arm.mdx
  docs/guides/gettingStarted/config-center.mdx
  docs/guides/gettingStarted/faq.mdx
  docs/guides/gettingStarted/internalDeployment.mdx
  docs/guides/solution/migrate.mdx
Labels: size/S

#238 feat: faq doc
  docs/guides/gettingStarted/cluster.mdx
  docs/guides/gettingStarted/faq.mdx
Labels: size/M
