Repository openimsdk/docs, pull requests merged in 2024-08, with the labels that each got.

#140 feat: prometheus import path update
  docs/guides/gettingStarted/admin.mdx
Labels: size/M

#141 fix: picture path
  docs/guides/gettingStarted/admin.mdx
Labels: size/XS

#143 fix: add prometheus config edit illustrate
  docs/guides/gettingStarted/admin.mdx
Labels: size/L

#142 feat: update api docs to v3.8
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/conversationManagement/setConversations.mdx
  docs/restapi/apis/friendsManagement/getSentApplication.mdx
  docs/restapi/apis/friendsManagement/importFriend.mdx
  docs/restapi/apis/friendsManagement/processApplication.mdx
  docs/restapi/apis/friendsManagement/sendApplication.mdx
  docs/restapi/apis/friendsManagement/updateFriendRemark.mdx
  docs/restapi/commonFields.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/getOwnerConversation.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/conversationManagement/setConversations.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/getSentApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/importFriend.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/processApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/sendApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/updateFriendRemark.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/commonFields.mdx
  scripts/githooks/commit-msg.sh
  scripts/githooks/pre-commit.sh
  scripts/githooks/pre-push.sh
Labels: size/XXL

#145 fix: nginx minio url
  docs/guides/gettingStarted/nginxDomainConfig.mdx
Labels: size/XS

#146 fix: prometheus questions
  docs/guides/gettingStarted/admin.mdx
Labels: size/M

#148 docs: update `gettingStarted` module in EN docs.
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/jssdk.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/admin.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/dashboard6.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/dashboard7.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/dashboard8.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/assets/dashboard9.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/dockerCompose.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/env-comp.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/imSourceCodeDeployment.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/jssdk.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/k8s-deployment.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/nginxDomainConfig.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/quickTestServer.mdx
  package.json
Labels: size/XXL

#149 fix: solve error
  docs/guides/gettingStarted/admin.mdx
Labels: size/M

#150 fix: fix error.
  docs/guides/gettingStarted/admin.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/gettingStarted/admin.mdx
Labels: size/M

#152 docs: update batch send message.
  docs/restapi/apis/messageManagement/batchSendMessage.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/messageManagement/batchSendMessage.mdx
Labels: size/L
