Repository openimsdk/docs, pull requests merged in 2024-09, with the labels that each got.

#156 docs: update user and group management API documentation
  docs/restapi/apis/userManagement/updateUserInfoEx.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/setGroupInfoEX.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfoEx.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExBefore.mdx
Labels: size/L

#160 feat: update workflows contents.
  .github/workflows/auto-assign-issue.yml
  .github/workflows/cla-assistant.yml
  .github/workflows/cla.yml
  .github/workflows/help-comment-issue.yml
  .github/workflows/issue-robot.yml
  .github/workflows/issue-translator.yml
  .github/workflows/remove-unused-labels.yml
  .github/workflows/reopen-issue.yml
  .github/workflows/stale.yml
Labels: size/L

#162 docs: update webhook docs in user and relation.
  docs/restapi/introduction.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeBefore.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/removeBlack.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
  docs/sdks/introduction.mdx
Labels: size/XXL

#163 feat: fix doc
  docs/restapi/webhooks/group/applyJoinGroupBefore.mdx
  docs/restapi/webhooks/group/createAfter.mdx
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/disMissGroupAfter.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/memberJoinGroupBefore.mdx
  docs/restapi/webhooks/group/quitGroup.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/group/sendGroupMsgBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx
  docs/restapi/webhooks/group/setMemberInfoAfter.mdx
  docs/restapi/webhooks/group/setMemberInfoBefore.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/msg/msgModify.mdx
  docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx
  docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
Labels: size/XL

#164 docs: update secret contents path.
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/userManagement/userRegister.mdx
Labels: size/S

#165 fix: update webhook config field contents.
  docs/restapi/webhooks/group/applyJoinGroupBefore.mdx
  docs/restapi/webhooks/group/createAfter.mdx
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/disMissGroupAfter.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/memberJoinGroupBefore.mdx
  docs/restapi/webhooks/group/quitGroup.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/group/sendGroupMsgBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx
  docs/restapi/webhooks/group/setMemberInfoAfter.mdx
  docs/restapi/webhooks/group/setMemberInfoBefore.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/msg/msgModify.mdx
  docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx
  docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeBefore.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/removeBlack.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
Labels: size/M

#166 docs: opid intro update.
  docs/restapi/apis/authenticationManagement/forceLogout.mdx
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/friendsManagement/addBlackList.mdx
  docs/restapi/apis/friendsManagement/checkFriend.mdx
  docs/restapi/apis/friendsManagement/deleteBlackList.mdx
  docs/restapi/apis/friendsManagement/deleteFriend.mdx
  docs/restapi/apis/friendsManagement/getBlackList.mdx
  docs/restapi/apis/friendsManagement/getFriendList.mdx
  docs/restapi/apis/friendsManagement/getRecvApplication.mdx
  docs/restapi/apis/friendsManagement/getSentApplication.mdx
  docs/restapi/apis/friendsManagement/importFriend.mdx
  docs/restapi/apis/friendsManagement/processApplication.mdx
  docs/restapi/apis/friendsManagement/sendApplication.mdx
  docs/restapi/apis/friendsManagement/setFriendRemark.mdx
  docs/restapi/apis/friendsManagement/updateFriends.mdx
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/checkUserRegistered.mdx
  docs/restapi/apis/userManagement/getSpecifiedUser.mdx
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/getUserIDList.mdx
  docs/restapi/apis/userManagement/getUserList.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatusDetail.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/updateGlobalRemind.mdx
  docs/restapi/apis/userManagement/updateNotificationAccount.mdx
  docs/restapi/apis/userManagement/updateUserInfo.mdx
  docs/restapi/apis/userManagement/updateUserInfoEx.mdx
  docs/restapi/apis/userManagement/userRegister.mdx
  docs/restapi/webhooks/group/memberJoinGroupBefore.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
Labels: size/M

#169 Webhook
  docs/guides/gettingStarted/admin.mdx
  docs/guides/gettingStarted/nginxDomainConfig.mdx
  docs/restapi/commonFields.mdx
  docs/restapi/webhooks/group/applyJoinGroupBefore.mdx
  docs/restapi/webhooks/group/createAfter.mdx
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/disMissGroupAfter.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/memberJoinGroupBefore.mdx
  docs/restapi/webhooks/group/quitGroup.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/group/sendGroupMsgBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx
  docs/restapi/webhooks/group/setMemberInfoAfter.mdx
  docs/restapi/webhooks/group/setMemberInfoBefore.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/introduction.mdx
  docs/restapi/webhooks/msg/msgModify.mdx
  docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx
  docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeBefore.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/removeBlack.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
Labels: size/XL

#168 docs: remove deprecated API webhook callback.
  docs/restapi/apis/authenticationManagement/_category_.json
  docs/restapi/apis/authenticationManagement/forceLogout.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/conversationManagement/_category_.json
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/friendsManagement/_category_.json
  docs/restapi/apis/friendsManagement/addBlackList.mdx
  docs/restapi/apis/friendsManagement/checkFriend.mdx
  docs/restapi/apis/friendsManagement/deleteBlackList.mdx
  docs/restapi/apis/friendsManagement/deleteFriend.mdx
  docs/restapi/apis/friendsManagement/getBlackList.mdx
  docs/restapi/apis/friendsManagement/getFriendList.mdx
  docs/restapi/apis/friendsManagement/getRecvApplication.mdx
  docs/restapi/apis/friendsManagement/getSentApplication.mdx
  docs/restapi/apis/friendsManagement/importFriend.mdx
  docs/restapi/apis/friendsManagement/processApplication.mdx
  docs/restapi/apis/friendsManagement/sendApplication.mdx
  docs/restapi/apis/friendsManagement/setFriendRemark.mdx
  docs/restapi/apis/friendsManagement/updateFriends.mdx
  docs/restapi/apis/groupManagement/_category_.json
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
  docs/restapi/apis/messageManagement/_category_.json
  docs/restapi/apis/userManagement/_category_.json
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/checkUserRegistered.mdx
  docs/restapi/apis/userManagement/getSpecifiedUser.mdx
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/getUserIDList.mdx
  docs/restapi/apis/userManagement/getUserList.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatusDetail.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/updateGlobalRemind.mdx
  docs/restapi/apis/userManagement/updateNotificationAccount.mdx
  docs/restapi/apis/userManagement/updateUserInfo.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoEXAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoEXBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoExAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoExBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/setFriendRemark.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/setGroupInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/groupManagement/setGroupInfoEX.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfoEx.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoEXAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/group/setGroupInfoEXBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExAfter.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/webhooks/user/updateUserInfoExBefore.mdx
Labels: size/XXL

#171 feat: server doc
  docs/restapi/introduction.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
Labels: size/S

#158 feat: updated documentation
  docs/sdks/api/conversation/index.mdx
  docs/sdks/api/conversation/resetConversationGroupAtType.mdx
  docs/sdks/api/conversation/setConversationBurnDuration.mdx
  docs/sdks/api/conversation/setConversationPrivateChat.mdx
  docs/sdks/api/conversation/setConversationRecvMessageOpt.mdx
  docs/sdks/api/conversation/setConversations.mdx
  docs/sdks/api/relation/index.mdx
  docs/sdks/api/relation/updateFriends.mdx
  docs/sdks/api/user/index.mdx
  docs/sdks/api/user/setGlobalRecvMessageOpt.mdx
  docs/sdks/api/user/setSelfInfo.mdx
  docs/sdks/api/user/setSelfInfoEx.mdx
Labels: size/XXL

#174 docs: update docs.
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/userManagement/getUserIDList.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatusDetail.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/introduction.mdx
Labels: size/M

#175 docs: update docs.
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/userManagement/userRegister.mdx
Labels: size/XS

#176 fix: Server doc
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/conversationManagement/getSortedConversationList.mdx
  docs/restapi/apis/conversationManagement/setConversations.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroup.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroupMember.mdx
  docs/restapi/apis/groupManagement/createGroup.mdx
  docs/restapi/apis/groupManagement/dismissGroup.mdx
  docs/restapi/apis/groupManagement/getGroupApplicationListByUserID.mdx
  docs/restapi/apis/groupManagement/getGroupMemberList.mdx
  docs/restapi/apis/groupManagement/getGroupMembersInfo.mdx
  docs/restapi/apis/groupManagement/getGroupsInfo.mdx
  docs/restapi/apis/groupManagement/getJoinedGroupList.mdx
  docs/restapi/apis/groupManagement/getRecvGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/getUserReqGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/groupApplicationResponse.mdx
  docs/restapi/apis/groupManagement/inviteUserToGroup.mdx
  docs/restapi/apis/groupManagement/joinGroup.mdx
  docs/restapi/apis/groupManagement/kickGroup.mdx
  docs/restapi/apis/groupManagement/muteGroup.mdx
  docs/restapi/apis/groupManagement/muteGroupMember.mdx
  docs/restapi/apis/groupManagement/quitGroup.mdx
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
  docs/restapi/apis/groupManagement/setGroupMemberInfo.mdx
  docs/restapi/apis/groupManagement/transferGroup.mdx
  docs/restapi/apis/messageManagement/batchSendMessage.mdx
  docs/restapi/apis/messageManagement/deleteUserAllMessage.mdx
  docs/restapi/apis/messageManagement/revokeMessage.mdx
  docs/restapi/apis/messageManagement/sendMessage.mdx
  docs/restapi/introduction.mdx
Labels: size/L

#177 Feat server
  docs/restapi/apis/authenticationManagement/forceLogout.mdx
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/conversationManagement/getSortedConversationList.mdx
  docs/restapi/apis/conversationManagement/setConversations.mdx
  docs/restapi/apis/friendsManagement/addBlackList.mdx
  docs/restapi/apis/friendsManagement/checkFriend.mdx
  docs/restapi/apis/friendsManagement/deleteBlackList.mdx
  docs/restapi/apis/friendsManagement/deleteFriend.mdx
  docs/restapi/apis/friendsManagement/getBlackList.mdx
  docs/restapi/apis/friendsManagement/getFriendList.mdx
  docs/restapi/apis/friendsManagement/getRecvApplication.mdx
  docs/restapi/apis/friendsManagement/getSentApplication.mdx
  docs/restapi/apis/friendsManagement/importFriend.mdx
  docs/restapi/apis/friendsManagement/processApplication.mdx
  docs/restapi/apis/friendsManagement/sendApplication.mdx
  docs/restapi/apis/friendsManagement/setFriendRemark.mdx
  docs/restapi/apis/friendsManagement/updateFriends.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroup.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroupMember.mdx
  docs/restapi/apis/groupManagement/createGroup.mdx
  docs/restapi/apis/groupManagement/dismissGroup.mdx
  docs/restapi/apis/groupManagement/getGroupApplicationListByUserID.mdx
  docs/restapi/apis/groupManagement/getGroupMemberList.mdx
  docs/restapi/apis/groupManagement/getGroupMembersInfo.mdx
  docs/restapi/apis/groupManagement/getGroupsInfo.mdx
  docs/restapi/apis/groupManagement/getJoinedGroupList.mdx
  docs/restapi/apis/groupManagement/getRecvGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/getUserReqGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/groupApplicationResponse.mdx
  docs/restapi/apis/groupManagement/inviteUserToGroup.mdx
  docs/restapi/apis/groupManagement/joinGroup.mdx
  docs/restapi/apis/groupManagement/kickGroup.mdx
  docs/restapi/apis/groupManagement/muteGroup.mdx
  docs/restapi/apis/groupManagement/muteGroupMember.mdx
  docs/restapi/apis/groupManagement/quitGroup.mdx
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
  docs/restapi/apis/groupManagement/setGroupMemberInfo.mdx
  docs/restapi/apis/groupManagement/transferGroup.mdx
  docs/restapi/apis/messageManagement/batchSendMessage.mdx
  docs/restapi/apis/messageManagement/deleteUserAllMessage.mdx
  docs/restapi/apis/messageManagement/revokeMessage.mdx
  docs/restapi/apis/messageManagement/sendMessage.mdx
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/checkUserRegistered.mdx
  docs/restapi/apis/userManagement/getSpecifiedUser.mdx
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/getUserIDList.mdx
  docs/restapi/apis/userManagement/getUserList.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatusDetail.mdx
  docs/restapi/apis/userManagement/searchNotificationAccount.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/updateGlobalRemind.mdx
  docs/restapi/apis/userManagement/updateNotificationAccount.mdx
  docs/restapi/apis/userManagement/updateUserInfo.mdx
  docs/restapi/apis/userManagement/userRegister.mdx
  docs/restapi/commonFields.mdx
  docs/restapi/contentDescription.mdx
Labels: size/L

#178 docs: update docs contents.
  docs/restapi/apis/authenticationManagement/forceLogout.mdx
  docs/restapi/apis/authenticationManagement/getToken.mdx
  docs/restapi/apis/authenticationManagement/getUserToken.mdx
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/conversationManagement/getSortedConversationList.mdx
  docs/restapi/apis/conversationManagement/setConversations.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroup.mdx
  docs/restapi/apis/groupManagement/cancelMuteGroupMember.mdx
  docs/restapi/apis/groupManagement/createGroup.mdx
  docs/restapi/apis/groupManagement/dismissGroup.mdx
  docs/restapi/apis/groupManagement/getGroupApplicationListByUserID.mdx
  docs/restapi/apis/groupManagement/getGroupMemberList.mdx
  docs/restapi/apis/groupManagement/getGroupMembersInfo.mdx
  docs/restapi/apis/groupManagement/getGroupsInfo.mdx
  docs/restapi/apis/groupManagement/getJoinedGroupList.mdx
  docs/restapi/apis/groupManagement/getRecvGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/getUserReqGroupApplicationList.mdx
  docs/restapi/apis/groupManagement/groupApplicationResponse.mdx
  docs/restapi/apis/groupManagement/inviteUserToGroup.mdx
  docs/restapi/apis/groupManagement/joinGroup.mdx
  docs/restapi/apis/groupManagement/kickGroup.mdx
  docs/restapi/apis/groupManagement/muteGroup.mdx
  docs/restapi/apis/groupManagement/muteGroupMember.mdx
  docs/restapi/apis/groupManagement/quitGroup.mdx
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
  docs/restapi/apis/groupManagement/setGroupMemberInfo.mdx
  docs/restapi/apis/groupManagement/transferGroup.mdx
  docs/restapi/apis/messageManagement/deleteUserAllMessage.mdx
  docs/restapi/apis/messageManagement/revokeMessage.mdx
  docs/restapi/apis/messageManagement/sendMessage.mdx
  docs/restapi/apis/userManagement/addNotificationAccount.mdx
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineTokenDetail.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/userRegister.mdx
  docs/restapi/commonFields.mdx
  docs/sdks/api/group/setGroupMemberInfo.mdx
  docs/sdks/api/message/createCardMessage.mdx
  docs/sdks/api/relation/searchFriends.mdx
  docs/sdks/api/user/setSelfInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getUserOnlineTokenDetail.mdx
Labels: size/L

#180 refactor: third and friends update.
  docs/sdks/api/conversation/index.mdx
  docs/sdks/api/conversation/setConversation.mdx
  docs/sdks/api/index.mdx
  docs/sdks/api/message/index.mdx
  docs/sdks/api/relation/checkFriend.mdx
  docs/sdks/api/relation/getFriendApplicationListAsApplicant.mdx
  docs/sdks/api/relation/getFriendApplicationListAsRecipient.mdx
  docs/sdks/api/third/index.mdx
  docs/sdks/api/third/logs.mdx
  docs/sdks/api/third/setAppBadge.mdx
  docs/sdks/api/third/updateFcmToken.mdx
  docs/sdks/api/third/uploadFile.mdx
  docs/sdks/api/third/uploadLogs.mdx
  docs/sdks/api/user/getUsersInfo.mdx
  docs/sdks/api/user/index.mdx
  docs/sdks/api/user/networkStatusChanged.mdx
  docs/sdks/api/user/setAppBackgroundStatus.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/index.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/setConversation.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/message/index.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/third/setAppBadge.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/third/uploadFile.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/getUsersInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/index.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/networkStatusChanged.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/setAppBackgroundStatus.mdx
Labels: size/XL

#179 fix: platformID
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
Labels: size/S

#182 fix: platformID
  docs/restapi/apis/userManagement/getUserOnlineStatus.mdx
  docs/restapi/apis/userManagement/getUserOnlineTokenDetail.mdx
Labels: size/XS

#187 docs: update friend api
  docs/sdks/api/relation/getFriendList.mdx
  docs/sdks/api/relation/getFriendListPage.mdx
  docs/sdks/api/relation/getSpecifiedFriendsInfo.mdx
  docs/sdks/api/user/getUsersInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendList.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendListPage.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getSpecifiedFriendsInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/getUsersInfo.mdx
Labels: size/L

#186 docs: update content
  docs/restapi/apis/authenticationManagement/getToken.mdx
Labels: size/XS

#189 fix: doc
  docs/restapi/apis/friendsManagement/addBlackList.mdx
  docs/restapi/apis/friendsManagement/deleteBlackList.mdx
  docs/restapi/apis/friendsManagement/deleteFriend.mdx
  docs/restapi/apis/friendsManagement/importFriend.mdx
  docs/restapi/apis/friendsManagement/processApplication.mdx
  docs/restapi/apis/friendsManagement/sendApplication.mdx
  docs/restapi/apis/friendsManagement/setFriendRemark.mdx
  docs/restapi/apis/friendsManagement/updateFriends.mdx
  docs/restapi/apis/userManagement/checkUserRegistered.mdx
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
  docs/restapi/apis/userManagement/updateGlobalRemind.mdx
  docs/restapi/apis/userManagement/updateUserInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/setFriendRemark.mdx
Labels: size/L

#188 fix: doc
  docs/restapi/apis/groupManagement/getGroupApplicationListByUserID.mdx
  docs/restapi/apis/groupManagement/kickGroup.mdx
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
  docs/restapi/apis/messageManagement/batchSendMessage.mdx
  docs/restapi/apis/messageManagement/sendMessage.mdx
  docs/restapi/commonFields.mdx
  docs/restapi/contentDescription.mdx
  docs/restapi/webhooks/example.mdx
Labels: size/M

#190 docs: update docs about android
  docs/sdks/api/conversation/setConversation.mdx
  docs/sdks/api/group/setGroupInfo.mdx
  docs/sdks/api/group/setGroupMemberInfo.mdx
  docs/sdks/api/relation/getFriendList.mdx
  docs/sdks/api/relation/getFriendListPage.mdx
  docs/sdks/api/relation/getSpecifiedFriendsInfo.mdx
  docs/sdks/api/relation/updateFriends.mdx
  docs/sdks/api/user/getUsersInfo.mdx
  docs/sdks/api/user/setSelfInfo.mdx
  docs/sdks/class/conversation/conversationReq.mdx
  docs/sdks/class/group/SetGroupMemberInfo.mdx
  docs/sdks/class/relation/updateFriendsReq.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/setConversation.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/group/setGroupMemberInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendList.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendListPage.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getSpecifiedFriendsInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/updateFriends.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/getUsersInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/user/setSelfInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/class/conversation/conversationReq.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/class/group/SetGroupMemberInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/class/relation/updateFriendsReq.mdx
Labels: size/XL

#192 feat: doc
  docs/guides/assets/br-cpu.png
  docs/guides/assets/br-login.png
  docs/guides/assets/br-mem.png
  docs/guides/assets/br-msg.png
  docs/guides/benchmark_test.mdx
  docs/guides/gettingStarted/dockerCompose.mdx
  docs/restapi/apis/groupManagement/createGroup.mdx
  docs/restapi/commonFields.mdx
  docs/restapi/webhooks/group/applyJoinGroupBefore.mdx
  docs/restapi/webhooks/group/createAfter.mdx
  docs/restapi/webhooks/group/createBefore.mdx
  docs/restapi/webhooks/group/disMissGroupAfter.mdx
  docs/restapi/webhooks/group/groupMsgRead.mdx
  docs/restapi/webhooks/group/inviteJoinGroupBefore.mdx
  docs/restapi/webhooks/group/joinGroupAfter.mdx
  docs/restapi/webhooks/group/killGroupMember.mdx
  docs/restapi/webhooks/group/memberJoinGroupBefore.mdx
  docs/restapi/webhooks/group/quitGroup.mdx
  docs/restapi/webhooks/group/sendGroupMsgAfter.mdx
  docs/restapi/webhooks/group/sendGroupMsgBefore.mdx
  docs/restapi/webhooks/group/setGroupInfoAfter.mdx
  docs/restapi/webhooks/group/setGroupInfoBefore.mdx
  docs/restapi/webhooks/group/setMemberInfoAfter.mdx
  docs/restapi/webhooks/group/setMemberInfoBefore.mdx
  docs/restapi/webhooks/group/transferGroupOwnerAfter.mdx
  docs/restapi/webhooks/introduction.mdx
  docs/restapi/webhooks/msg/msgModify.mdx
  docs/restapi/webhooks/msg/sendSingleMsgAfter.mdx
  docs/restapi/webhooks/msg/sendSingleMsgBefore.mdx
  docs/restapi/webhooks/msg/singleMsgRead.mdx
  docs/restapi/webhooks/msg/singleMsgRevokeAfter.mdx
  docs/restapi/webhooks/push/offlinePushBefore.mdx
  docs/restapi/webhooks/push/onlinePushBefore.mdx
  docs/restapi/webhooks/relationship/addBlack.mdx
  docs/restapi/webhooks/relationship/addFriendAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeAfter.mdx
  docs/restapi/webhooks/relationship/addFriendAgreeBefore.mdx
  docs/restapi/webhooks/relationship/addFriendBefore.mdx
  docs/restapi/webhooks/relationship/deleteFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendAfter.mdx
  docs/restapi/webhooks/relationship/importFriendsBefore.mdx
  docs/restapi/webhooks/relationship/removeBlack.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkAfter.mdx
  docs/restapi/webhooks/relationship/setFriendRemarkBefore.mdx
  docs/restapi/webhooks/user/updateUserInfoAfter.mdx
  docs/restapi/webhooks/user/updateUserInfoBefore.mdx
  docs/restapi/webhooks/user/userOffline.mdx
  docs/restapi/webhooks/user/userOnline.mdx
  docs/restapi/webhooks/user/userRegisterAfter.mdx
  docs/restapi/webhooks/user/userRegisterBefore.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/assets/br-cpu.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/assets/br-login.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/assets/br-mem.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/assets/br-msg.png
  i18n/en/docusaurus-plugin-content-docs-guides/current/benchmark_test.mdx
  package.json
Labels: size/XL
