Repository openimsdk/docs, pull requests merged in 2024-10, with the labels that each got.

#197 fix: group
  docs/restapi/apis/groupManagement/setGroupInfo.mdx
Labels: size/XS

#199 fix: The return value problem of input status. (#198)
  docs/sdks/api/conversation/getInputStates.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/getInputStates.mdx
Labels: size/S

#200 docs: update api doc
  docs/sdks/api/conversation/changeInputStates.mdx
  docs/sdks/api/conversation/getInputStates.mdx
  docs/sdks/api/group/getJoinedGroupListPage.mdx
  docs/sdks/api/group/getUsersInGroup.mdx
  docs/sdks/api/group/isJoinGroup.mdx
  docs/sdks/api/third/logs.mdx
  docs/sdks/api/third/uploadLogs.mdx
  docs/sdks/callback/onInputStatusChanged.mdx
  docs/sdks/class/conversation/inputStatusChangedData.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/changeInputStates.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/getInputStates.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/group/getJoinedGroupListPage.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/group/getUsersInGroup.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/group/isJoinGroup.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/third/logs.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/third/uploadLogs.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/callback/onInputStatusChanged.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/class/conversation/inputStatusChangedData.mdx
Labels: size/XXL

#201 docs: remove space.
  docs/restapi/apis/userManagement/getSubscribeUsersStatus.mdx
Labels: size/XS

#202 docs: improve docs
  docs/restapi/apis/userManagement/subscribeUsersStatus.mdx
Labels: size/XS

#203 fix: conv
  docs/restapi/apis/conversationManagement/getOwnerConversation.mdx
  docs/restapi/apis/conversationManagement/setConversations.mdx
Labels: size/XS

#206 fix: the return value problem of get friends list. (#205)
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendList.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getFriendListPage.mdx
Labels: size/S

#208 fix: docker
  docs/guides/gettingStarted/dockerCompose.mdx
Labels: size/XS

#210 fix: doc
  docs/guides/gettingStarted/admin.mdx
  docs/restapi/webhooks/user/userOffline.mdx
Labels: size/XS

#209 docs: update en docs by Server API.
  docs/restapi/commonConfigs.mdx
  docs/restapi/commonFields.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/authenticationManagement/forceLogout.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/authenticationManagement/getAdminToken.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/authenticationManagement/getUserToken.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/addBlackList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/checkFriend.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/deleteBlackList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/deleteFriend.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/getBlackList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/getFriendList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/getRecvApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/getSentApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/importFriend.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/processApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/sendApplication.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/friendsManagement/updateFriends.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/addNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/checkUserRegistered.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getSpecifiedUser.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getSubscribeUsersStatus.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getUserIDList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getUserList.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getUserOnlineStatus.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/getUserOnlineTokenDetail.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/searchNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/subscribeUsersStatus.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateGlobalRemind.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateNotificationAccount.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/updateUserInfo.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/apis/userManagement/userRegister.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/commonConfigs.mdx
  i18n/en/docusaurus-plugin-content-docs-restapi/current/commonFields.mdx
Labels: size/XXL

#204 update android api doc
  docs/sdks/api/conversation/changeInputStates.mdx
  docs/sdks/api/conversation/getInputStates.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/changeInputStates.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/conversation/getInputStates.mdx
Labels: size/L

#213 fix: get black list api
  docs/sdks/api/relation/getBlackList.mdx
  i18n/en/docusaurus-plugin-content-docs-sdks/current/api/relation/getBlackList.mdx
Labels: size/M

#215 fix: test param change
  docs/guides/benchmark_test.mdx
  i18n/en/docusaurus-plugin-content-docs-guides/current/benchmark_test.mdx
Labels: size/S
