Repository openimsdk/docs, pull requests merged in 2025-05, with the labels that each got.

#258 fix spelling mistake of "compose" in step 6
  docs/guides/gettingStarted/internalDeployment.mdx
Labels: size/XS

#273 feat: file storage
  docs/blog/golang/architectural/3.mdx
Labels: size/L

#275 fix: InputStatusChangedData
  docs/blog/golang/architectural/3.mdx
  docs/sdks/callback/onInputStatusChanged.mdx
  docs/sdks/class/conversation/inputStatusChangedData.mdx
Labels: size/L

#276 docs: update class specification of messages.
  docs/sdks/class/message/GetAdvancedHistoryMessageListParams.mdx
  docs/sdks/class/message/SearchMessagesParams.mdx
  docs/sdks/class/message/atInfo.mdx
  docs/sdks/class/message/attachedInfoElem.mdx
  docs/sdks/class/message/conversationArgs.mdx
  docs/sdks/class/message/fileElem.mdx
  docs/sdks/class/message/groupHasReadInfo.mdx
  docs/sdks/class/message/index.mdx
  docs/sdks/class/message/locationElem.mdx
  docs/sdks/class/message/mergeElem.mdx
  docs/sdks/class/message/messageInfo.mdx
  docs/sdks/class/message/notificationElem.mdx
  docs/sdks/class/message/offlinePushInfo.mdx
  docs/sdks/class/message/pictureElem.mdx
  docs/sdks/class/message/pictureInfo.mdx
  docs/sdks/class/message/quoteElem.mdx
  docs/sdks/class/message/receiptInfo.mdx
  docs/sdks/class/message/revokedInfo.mdx
  docs/sdks/class/message/searchResultItem.mdx
  docs/sdks/class/message/soundElem.mdx
  docs/sdks/class/message/videoElem.mdx
  docs/sdks/enum/logLevel.mdx
  docs/sdks/enum/messageFrom.mdx
Labels: size/XXL

#277 feat: chat cluster
  docs/guides/gettingStarted/cluster.mdx
Labels: size/L
